# Proyecto
sonar.projectKey=JackySeve_PocketMetrics
sonar.organization=jackyseve
sonar.projectName=PocketMetrics
sonar.projectVersion=1.0
sonar.token=a51dd68bb4ca7c4d84cfff6a4622f1ba8d55d47a

# Ruta de los archivos fuente y pruebas
sonar.sources=lib
sonar.tests=test

# Excluir archivos de prueba y otros innecesarios
sonar.exclusions=**/test/**, **/*.g.dart

# Informe de cobertura de código
sonar.dart.coverage.reportPaths=coverage/lcov.info

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8

# URL de SonarCloud
sonar.host.url=https://sonarcloud.io

# Modo de análisis (usar FLUTTER si el proyecto es de Flutter)
sonar.dart.analyzer.mode=FLUTTER

# Reporte de análisis
sonar.dart.analyzer.report.mode=MACHINE
