// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EnxF2lLrQPmHh0BdBzJWcXs6Y60RsfA',
    appId: '1:64964084126:web:bbfa6978370f675293568f',
    messagingSenderId: '64964084126',
    projectId: 'pocketmetrics',
    authDomain: 'pocketmetrics.firebaseapp.com',
    storageBucket: 'pocketmetrics.appspot.com',
    measurementId: 'G-WK8KLQYHYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmfR2nrr1LR-N--d6mZCXj9TYFmHRrhrE',
    appId: '1:64964084126:android:1dccae960796f2b893568f',
    messagingSenderId: '64964084126',
    projectId: 'pocketmetrics',
    storageBucket: 'pocketmetrics.appspot.com',
  );

}